#!/bin/sh
# waits for a random time between 5 and 15 minutes, 
# then curls for a random Wikipedia page in URL https://en.wikipedia.org/wiki/Special:Random 
# and saves the page content to the folder /usr/src/app/curled

set -e # exit immediately if a command exits with a non-zero status

# Countdown random between 5 and 15 minutes
echo "updater started"
NUMBER_OF_SECONDS=$(( ($RANDOM % 600) + 300 ))
for i in $(seq $NUMBER_OF_SECONDS -7 1); do 
  echo "will update in $(( i / 60 )) min $(( i % 60 )) s"
  sleep 7
done

string=$(curl -I https://en.wikipedia.org/wiki/Special:Random | grep location)
url=${string#"location: "}
url="${url//$'\r'/}"
echo "updating served website with $url"
# '/usr/src/app/curled' is the path mounted in deployment.yaml and will so exist, so no need to $mkdir curled
curl -o curled/index.html $url

# keep the container alive
while true; do
  sleep 3600
done
